### ISSUE TITLE
Redirect page doesn't work.

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#21]
After running solutions, please go to Redirect page. Then in Google Chrome Console we will see: 
`puppet-redirect.html:1 GET http://localhost:8080/sys/puppet-redirect/src/puppet-redirect.html 404 (Not Found)`

**Comment by warpech** [comment]
This is because of the change of path in `puppet-redirect` project to `/sys/puppet-redirect/puppet-redirect.html` after Starcounter stable 2.1.177 was released.

Until the next stable, maybe we should actually import both paths?

```html
<link rel="import" href="/sys/puppet-redirect/puppet-redirect.html">
<link rel="import" href="/sys/puppet-redirect/src/puppet-redirect.html">
```

I think the best solution would be to add `/sys/puppet-redirect/src/puppet-redirect.html` back to Starcounter /sys/, just with a comment saying "You are using `puppet-redirect` from a deprecated path. Please change `/sys/puppet-redirect/src/puppet-redirect.html` to `/sys/puppet-redirect/puppet-redirect.html` in your HTML template or things may break in future.

**Comment by warpech** [comment]
Duplicate: https://github.com/StarcounterSamples/KitchenSink/issues/12

**Comment by warpech** [comment]
@aloscha, when marking issue for code review, could you also paste a link to the branch? Like this: https://github.com/StarcounterSamples/KitchenSink/tree/Redirect_page_%2321

**Comment by warpech** [comment]
@tomalec, don't you think that a solution to these problems would be to include the Custom Element definition HTML at two locations for some time? One of them might have a warning that it's deprecated.

Or is there any problem if two partials in my app import an element from two locations?

**Comment by tomalec** [comment]
> Or is there any problem if two partials in my app import an element from two locations?

AFAIK There will be a browser error thrown that you are trying to register already registered element.

**Comment by aloscha** [comment]
@warpech could we merged https://github.com/StarcounterSamples/KitchenSink/tree/Redirect_page_%2321 into master?

**Comment by warpech** [comment]
> AFAIK There will be a browser error thrown that you are trying to register already registered element.

Yes, but the error does not crash the page. The first registered element wins. So I think that my proposal might actually work. This will solve the problem for all of the apps. WDYT?

> @warpech could we merged https://github.com/StarcounterSamples/KitchenSink/tree/Redirect_page_%2321 into master?

No, because as said before, I would like KitchenSink to work in Starcounter stable by default. If @tomalec agrees then we can use bilocation of `puppet-redirect.html` to solve this problem. Or postpone discussion until Starcounter 2.2 is released, which should be in April anyway.

**Comment by miyconst** [comment]
>No, because as said before, I would like KitchenSink to work in Starcounter stable by default.

KitchenSink already does not work with Starcounter stable. The file upload example requires `Polymer ~1.3.0`.

**Comment by warpech** [comment]
We should always assume our apps to work with Starcounter stable. Otherwise write it very clearly about it and explain why.

**Comment by tomalec** [comment]
If it does not crash the page, I'm fine with bilocation + explicit warning message as interim step.

**Comment by warpech** [comment]
Do you agree to release bilocation as puppet-redirect 0.4.1? I think there is no harm in that.

**Comment by tomalec** [comment]
I do.

**Comment by warpech** [comment]
Done

**Comment by warpech** [comment]
The commit that fixes this issue (https://github.com/StarcounterSamples/KitchenSink/tree/Redirect_page_%2321) can be merged (**with the comment removed**) after Starcounter 2.2 is released. 

Until then, there is no problem anymore starting from tomorrows nightly (Starcoutner 2.1.1572 and higher).

**Comment by warpech** [comment]
@aloscha, since 2.2 was released last week, we can now merge the fix to `master` and close this issue. Can you do this?

**Comment by aloscha** [comment]
@warpech it's already works on master (tested in SC stable version), so I think we could close issue.

**Comment by warpech** [comment]
Sure, thanks!
