### ISSUE TITLE
Refactor Selenium Tests

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#28]
- Handle edge browser (if current os isn't 10 then ignore)
- After get new repo from git, we have 3.2 nunit version (in tutorial 2.6.4)
- Naming of classes

**Comment by aloscha** [comment]
@warpech I've add 3.2 nunit test as before. I check it and everything works well.
So maybe change it in Guides on Starcounter.io site?

**Comment by aloscha** [comment]
The "Handle edge browser" I based on that stack post http://stackoverflow.com/questions/33594401/how-can-i-detect-if-microsoft-edge-is-installed also find something like that http://stackoverflow.com/questions/32357874/finding-installed-browsers-microsoft-edge but there is need to looking into registry. What do you think @warpech

**Comment by warpech** [comment]
> @warpech I've add 3.2 nunit test as before. I check it and everything works well.

I see that `package.config` still refers to NUnit `2.6.4`. Did you push all changes?

I added one comment to the commit: https://github.com/StarcounterSamples/KitchenSink/commit/f751d99c2460905faea5605e083601f25f5b0e92

But most importantly, Windows 10 detection does not work well for me! For some strange reason, Visual Studio thinks I am on Windows 8. We can investigate tomorrow on my laptop if you need. Maybe this is because I upgraded from Windows 8 to 10? 

See the attached screenshot:

![2016-04-07 01_03_56-greenshot](https://cloud.githubusercontent.com/assets/566463/14335635/2352fd78-fc5d-11e5-97c8-0b7f8a0d2fae.png)

**Comment by aloscha** [comment]
Ok, let's do it tomorrow.
