### ISSUE TITLE
Pattern for input validation

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#6]
WDYT?

```json
{
  "ProjectNumber$": "",
  "Errors": [
        {
            "ErrorMessage": "Project number cannot be empty",
            "MemberNames": [ "ProjectNumber$" ]
        }
    ]
}
```

```html
<template>
    <template is="dom-bind">
        <style>
            div.errorMsg[title] {
                color: red;
            }

                div.errorMsg[title] input {
                    border: 1px solid red;
                }
        </style>

        <div class="errorMsg" title$="{{getErrorMessage(model.Errors.*, 'ProjectNumber')}}">
            <div class="form-group">
                <label for="ProjectNumber">Project Number</label>
                <input type="text" class="form-control" id="ProjectNumber" placeholder="Project number" value="{{model.ProjectNumber$::input}}">
            </div>
        </div>

        <dom-bind-notifier observed-object="{{model}}" path="model" deep></dom-bind-notifier>
    </template>
    <script>
        (function init(template) {
            template.getErrorMessage = function (errors, elementId) {
                var str = "";
                if (errors.base) {
                    errors.base.forEach(function (error) {
                        if (error.MemberNames.indexOf(elementId) > -1) {
                            str = error.ErrorMessage;
                        }
                    })
                }
                return str || false;
            };
        })(document.currentScript.previousElementSibling);
    </script>
</template>
```

**Comment by tomalec** [comment]
LGTM,

But i think we could try make it even easier if someone would like to stick to our convention:
```html
<template>
    <template is="dom-bind">
        <style>
            juicy-error[title] {
                color: red;
            }

                juicy-error[title] input {
                    border: 1px solid red;
                }
        </style>

        <juicy-error errors="{{model.Errors.*}} input-id="ProjectNumber">
            <div class="form-group">
                <label for="ProjectNumber">Project Number</label>
                <input type="text" class="form-control" id="ProjectNumber" placeholder="Project number" value="{{model.ProjectNumber$::input}}">
            </div>
        </juicy-error>

        <dom-bind-notifier observed-object="{{model}}" path="model" deep></dom-bind-notifier>
    </template>
</template>
```
If Polymer would support such thing. 
With Aurelia it should be doable

**Comment by jwillmer** [comment]
Link to the problem: [How to get a event in JS if some JSON property changes?](https://github.com/Starcounter/Starcounter/issues/3145#issuecomment-161932462)

I think the solution of @warpech solves the issue of noticing an property change event but in order to remove js logic from a script block it generates long and unreadable html elements. @tomalec proposal is a little bit better but espacially the ```{{model.Errors.*}}``` looks odd to me.

But it also might be the example that makes the look&feel odd ;-)

**Comment by tomalec** [comment]
`model.Errors.*` is now regular Polymer thing. However, I'm not 100% sure it will work for our case, but as I get Polymer guys, doing such things *is supposed* to be supported ;)

**Comment by warpech** [comment]
Asisgning @aloscha, who has a proposal how to use https://github.com/JeremySkinner/FluentValidation as a pattern

**Comment by aloscha** [comment]
I've create simple demo inside kitchensink, because I need some validation inside other project. For validation engine I used FluentValidation and write some wrapper to use it with Starcounter.

So to validate some viewmodel we just call `Validate(Json)`.
For each property we could write rule with some validator like `NotEmpty`, `Length` etc. (whole list here https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators, even custom validators are supports).

Example, for property `name` we have validation rule: `RuleFor(item => item.Name).NotEmpty()`
But if we would like to have integration with error property we need to add `.BindError((item, err) => { item.ErrorName = err; })`

And that's all we need. So guys what do you think about it?

![image](https://cloud.githubusercontent.com/assets/5141943/16472109/f4dc4e94-3e61-11e6-81d1-102594f2b82d.png)

**Comment by miyconst** [comment]
@aloscha I like the `FluentValidation` and your example.

**Comment by aloscha** [comment]
Example of usage is in KitchenSink - ValidationPage
