### ISSUE TITLE
Add example of self disabling button while server processes click event

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/KitchenSink#66]
>How to get a callback from server once server responded on a button click

This question has been asked so many times. We need to add an example of such button to this project.

https://github.com/Starcounter/Starcounter/issues/3858#issuecomment-251078202

**Comment by miyconst** [comment]
@Joltrix please take this issue when you get tired/border by other projects.

**Comment by Joltrix** [comment]
@miyconst Is this okay?

I added "an extra button" with a delay, just to kinda display (slower) what's happening. Because the server responds to fast sometimes, so it feels like nothing happened.

And is the "text" okay? Or do you want me to provide more information about how it works? (I tried to keep it as short as possible, to make it similar to the other "entrys"

**Comment by miyconst** [comment]
Looks good to me, except the `float: left`styles. Can you style it with flex or make one button on a line?

**Comment by Joltrix** [comment]
Okay, will try to fix it :)

**Comment by Joltrix** [comment]
Fixed in [StarcounterSamples/KitchenSink/0ab4415](https://github.com/StarcounterSamples/KitchenSink/commit/0ab4415515a9f2bdb1c7c704592ebddc9ce05940)

**Comment by miyconst** [comment]
Thanks @Joltrix, merged. Now you can remove the branch.
